### ISSUE TITLE
Can't connect to websocket

### ISSUE THREAD

**Issue by emaniacs** [noraesae/orange-cat#7]
Hello @noraesae i got error if i opened the url with 127.0.0.1.

In this [file](https://github.com/noraesae/orange-cat/blob/master/template.go#L34) instead of using 

`var conn = new WebSocket("ws://localhost:%[2]d/%[1]s");`

i prefer to use javascript function location,

`var conn = new WebSocket("ws://"+location.host+"/%[1]s");`

Javascript *location* info. https://developer.mozilla.org/en-US/docs/Web/API/Window/location

**Comment by noraesae** [comment]
Thanks!

**Comment by emaniacs** [comment]
Great.
